Add decorators
Rishi-Mishra0704/ruby-class pull request #2
Opened 2023-05-22 15:46 UTC by Rishi-Mishra0704

# Decorators

**Create a class Nameable.**
Implement a method called correct_name that will raise a NotImplementedError.

**Turn Person class to Nameable**
Make sure that your Person class inherits from Nameable
Make sure that this class has a method correct_name implemented. It should simply return the name attribute.

**Prepare CapitalizeDecorator and TrimmerDecorator**
**_For the CapitalizeDecorator:_**
Create a class that inherits from the base Decorator class.
Implement a method correct_name that capitalizes the output of @nameable.correct_name.
**_For the TrimmerDecorator:_**
Create a class that inherits from the base Decorator class.
Implement a method correct_name that makes sure that the output of @nameable.correct_name has a maximum of 10 characters. If it's longer it should trim the word.

2023-05-22 15:55 UTC, frank1738 reviewed
Hi @Rishi-Mishra0704 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Your readme file is incomplete in some sections. Kindly complete it to have a professional readme.

![image](https://github.com/Rishi-Mishra0704/ruby-class/assets/98453979/9250c77a-cdf2-45ca-8bd3-1f1a753826a5)

![image](https://github.com/Rishi-Mishra0704/ruby-class/assets/98453979/d7ba69fd-8c8a-4d54-b17d-dd80886b60d0)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-05-22 17:00 UTC, Olamarx requested changes
Hi @Rishi-Mishra0704, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights
- Linters passed ✔️
- Readme file professional ✔️
- All method and classes created ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-22 17:00 UTC, Olamarx commented on class/decorator.rb
> +  def initialize(nameable)
- [ ] You must have forgotten to add the GETTER and SETTER which can be easily done with the attr_accessor keyword. `attr_accessor :nameable`

2023-05-22 17:00 UTC, Olamarx commented on class/trimmer_decorator.rb
> +    super[0...10]
- [ ] I have two things to recommend here:
- First, you should remember that strings are index-based and as a result, if you want 10 characters, you should start from 0 to 9, not 10. So, it should be [0...9].
- Second is, you actually need a condition to check if the string is actually more than the number you are expecting before any action is done. We can achieve this with the use of ternary operator and it could look like
```
@nameable.correct_name.length > 10 ? @nameable.correct_name[0..9] : @nameable.correct_name
```

Kindly let me know if anything is vague to you.

2023-05-22 18:15 UTC, Rishi-Mishra0704 commented
Thank you

On Mon, May 22, 2023, 22:30 Olaoluwa Owoeye ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Rishi-Mishra0704 <https://github.com/Rishi-Mishra0704>,
>
> Good job so far, indeed you have spent time on this project!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> <https://camo.githubusercontent.com/e8dc1cd1bdef105014a7bd95718fbdb4a3244d39d36f9dbf8c36a8822117757a/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966>
> Highlights
>
>    - Linters passed ✔️
>    - Readme file professional ✔️
>    - All method and classes created ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In class/decorator.rb
> <https://github.com/Rishi-Mishra0704/ruby-class/pull/2#discussion_r1200761788>
> :
>
> > +require_relative 'nameable'
> +
> +class Decorator < Nameable
> +  def initialize(nameable)
>
>
>    - You must have forgotten to add the GETTER and SETTER which can be
>    easily done with the attr_accessor keyword. attr_accessor :nameable
>
> ------------------------------
>
> In class/trimmer_decorator.rb
> <https://github.com/Rishi-Mishra0704/ruby-class/pull/2#discussion_r1200774019>
> :
>
> > @@ -0,0 +1,7 @@
> +require_relative 'decorator'
> +
> +class TrimmerDecorator < Decorator
> +  def correct_name
> +    super[0...10]
>
>
>    - I have two things to recommend here:
>    - First, you should remember that strings are index-based and as a
>    result, if you want 10 characters, you should start from 0 to 9, not 10.
>    So, it should be [0...9].
>    - Second is, you actually need a condition to check if the string is
>    actually more than the number you are expecting before any action is done.
>    We can achieve this with the use of ternary operator and it could look like
>
> @nameable.correct_name.length > 10 ? @nameable.correct_name[0..9] : @nameable.correct_name
>
> Kindly let me know if anything is vague to you.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Rishi-Mishra0704/ruby-class/pull/2#pullrequestreview-1437023802>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3L77JEINT24BLO6ONZC5FTXHOLSHANCNFSM6AAAAAAYKUJICM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-23 04:07 UTC, Davidosky007 approved these changes
Hi @Rishi-Mishra0704 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Class decorated properly 👍 
* Well written PR 👍 
* No linter errors 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 16:06 UTC, merged